"""Initial schema — ViralFlux v2 (multi-tenant + credits).

Builds the entire schema directly from the SQLAlchemy model metadata so the
initial migration can never drift from the models. Future migrations are normal
autogenerated diffs against this baseline.

Revision ID: 001
Revises:
Create Date: 2026-06-16 00:00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# Ensure every model is imported so Base.metadata is fully populated.
import app.models  # noqa: F401
from app.core.database import Base

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
